# docs/openapi.yaml
openapi: 3.0.0
info:
  title: 피그말리온 다이어리 API
  description: 회사에서 좋았던 일을 기록하는 다이어리 서비스
  version: 1.0.0
  contact:
    name: 개발팀
    email: dev@company.com

servers:
  - url: https://umlnlzcebxiumpjdpvsq.supabase.co
    description: Supabase 서버

paths:
  /auth/v1/signup:
    post:
      summary: 회원가입
      tags: [인증]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  minLength: 6
                  example: "password123"
                data:
                  type: object
                  properties:
                    nickname:
                      type: string
                      example: "김개발"
      responses:
        '200':
          description: 회원가입 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string

  /auth/v1/token:
    post:
      summary: 로그인
      tags: [인증]
      parameters:
        - name: grant_type
          in: query
          required: true
          schema:
            type: string
            enum: [password]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: 로그인 성공

  /rest/v1/user_profiles:
    get:
      summary: 사용자 프로필 조회
      tags: [사용자]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 프로필 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    nickname:
                      type: string
                    push_enabled:
                      type: boolean
                    push_time:
                      type: string
                      format: time

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    apiKey:
      type: apiKey
      in: header
      name: apikey
